# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and Test

on:
  pull_request:
    branches: ['main', 'develop', 'stage']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

      - name: Build
      - run: npm run build

      - name: Test
      - run: npm run test:ci

      - name: Display Coverage
        uses: romeovs/lcov-reporter-action@v0.2.21
        with:
          github-token: ${{ secrets.REPO_TOKEN }}
          lcov-file: ./coverage/lcov.info
